### ISSUE TITLE
some difficulty implementing Shiny applications

### ISSUE THREAD

**Issue by profwilliammelo** [Eflores89/notionR#14]
Hello! I'm trying make deploy shiny apps with notionR package and I get the error: **lazy loading failed for package "notionR".** Exist a good way can I fixed it? Thank you for the package! Is very, very useful for me.

**Comment by Eflores89** [comment]
Hi, it's probably some local configuration that is producing the error. Try loading it outside of shiny on a new project before loading anything and see if it works. If it does, it's something in your application.
