### ISSUE TITLE
Any plans to create a pakgdown documentation site?

### ISSUE THREAD

**Issue by ran-codes** [Eflores89/notionR#16]
Hello! great pacakge. its a new year and I am trying to get into Notion because its got an awesome database UI experience. 

This seems like a great package to utilize it with R for data sceicent tasks. Any plans for a documentaion site for this package?

Thanks

**Comment by Eflores89** [comment]
Marking closed as I had a PR to help with this! sorry for the long wait time, i'm building this in very sparse spare time
